// Generated by scripts/fetch-news.mjs from https://arcraiders.com/news. Do not edit.
window.ARC_NEWS = [
 {
  "id": "pve-toggle-beta-test",
  "url": "https://arcraiders.com/news/pve-toggle-beta-test",
  "date": "2026-09-24",
  "tags": [],
  "thumb": "https://assets.arcraiders.com/article-cards/4382ddb0-bfc3-pve-toggle-card-600x200-600x200.png",
  "title": {
   "en": "We’re testing a PvE Toggle: here’s what it means for you"
  },
  "body": [
   {
    "type": "image",
    "html": "<img src=\"https://assets.arcraiders.com/media/2fcfcc36-537c-ARC-Raiders__Header-PvEToggle_1920x622-1024x332.jpg\" alt=\"\" loading=\"lazy\" width=\"1024\" height=\"332\">"
   },
   {
    "type": "html",
    "en": "<p>We’re excited to share that we will be testing a PvE matchmaking toggle in ARC Raiders, and it’s coming soon!</p>"
   },
   {
    "type": "html",
    "en": "<p>The test will run from <strong>October 13-20, 2026</strong>, giving players the option to choose between the classic ARC Raiders PvPvE experience or a PvE experience focused on co-op gameplay with other Raiders versus the ARC threat.</p>"
   },
   {
    "type": "html",
    "en": "<p>Before we get into the details of the test, we want to take a step back and explain how we got here, and why we’re exploring this feature now.</p>"
   },
   {
    "type": "html",
    "en": "<h3>The Vision of ARC Raiders</h3>"
   },
   {
    "type": "html",
    "en": "<p>When ARC Raiders was conceived seven years ago, the vision of the game was quite different. </p>"
   },
   {
    "type": "html",
    "en": "<p>We originally envisioned a raid-based PvE Co-op game with looting mechanics. While the concept showed promise, we ran into significant challenges, and eventually decided to reset the game and build the high-tension PvPvE Extraction adventure that you know today. (For the full story, we recommend watching the <a href=\"https://www.youtube.com/watch?v=tdorU3sjt_0\" target=\"_blank\" rel=\"noopener\"><strong>The Evolution of ARC Raiders EP1 - Finding ARC Raiders</strong></a>)</p>"
   },
   {
    "type": "html",
    "en": "<p>But when the game launched, we were pleasantly surprised; It wasn’t just extraction shooter fans who came to the Rust Belt, but a wide array of different players finding unique ways to enjoy the world. ARC Raiders became the “Extraction (Don’t) Shooter”, reaching a vibrant and diverse audience. This is something we’re very proud of here at Embark Studios.</p>"
   },
   {
    "type": "html",
    "en": "<p>As with all live games, the design should be an ongoing conversation with you, the players. Our goal is to stay true to the core principles on which ARC Raiders was built, but also respecting player choice and supporting different playstyles. </p>"
   },
   {
    "type": "image",
    "html": "<img src=\"https://assets.arcraiders.com/media/0bd8819b-7dec-PvE_toggle_blog-1024x576.jpg\" alt=\"\" loading=\"lazy\" width=\"1024\" height=\"576\">"
   },
   {
    "type": "html",
    "en": "<h3>What We’re Seeing</h3>"
   },
   {
    "type": "html",
    "en": "<p>At Embark we try to approach all key decisions from three different perspectives.<strong> What does the data indicate? What does the player feedback say? And what does our gut tell us?</strong> </p>"
   },
   {
    "type": "html",
    "en": "<p>Sometimes one perspective is more important than the other, but we try to triangulate our decisions between all three. There is no exact science, but as gamers ourselves, we always try to make the best decisions for the game and players.</p>"
   },
   {
    "type": "html",
    "en": "<p>If we look at the overall population of players and split them by how they most like to play, it looks like this:</p>"
   },
   {
    "type": "html",
    "en": "<ul><li>37% Friendly co-op players (this player group has grown consistently since launch).</li><li>27% Mixed players.</li><li>34% Pure PvP players (this player group has remained stable since launch).</li><li>Over 70% of Friendly players and even 40% of PvP players express a desire for fewer hostile encounters and 51% of the surveyed playerbase has expressed an interest in a dedicated PvE option.</li><li>There are clear friction points, with friendly players often attempting to avoid PvP entirely, and we hear frustration from certain groups of players around ratting and camping.</li></ul>"
   },
   {
    "type": "html",
    "en": "<p>We’re seeing a large and growing group of Raiders who come to the Rust Belt for the co-op and the ARC, not fighting with other Raiders. That group has become a core part of our community, so it’s important we learn how to support them properly rather than leave them working around the game</p>"
   },
   {
    "type": "html",
    "en": "<h3>Introducing the PvE Matchmaking Toggle Beta test</h3>"
   },
   {
    "type": "html",
    "en": "<p>To make a long story short, we’re going to be running a test with a PvE matchmaking toggle. This is how it will work:</p>"
   },
   {
    "type": "html",
    "en": "<ul><li>The test will run from <strong>October 13-20, 2026.</strong></li><li>During the test, you will be able to toggle between the classic ARC Raiders PvPvE experience and the PvE experience. </li><li>In the PvE experience there will be <strong>zero player-to-player damage</strong>, and the session is <strong>purely focused on the ARC threat and co-op social dynamics.</strong></li><li>PvE sessions will include <strong>Solos, Duos and Trios in the same session.</strong></li><li>We’re designing the system for<strong> seamless switching</strong>, play PvE for a relaxed solo session then switch back to PvPvE for a high tension match.</li><li>Some <strong>major conditions, Night Raids, Hidden Bunker, Locked Gate and Frigate will be excluded</strong> from the PvE matchmaking test. These are designed with higher tension in mind and rely on the uncertainty of encountering a variety of players.</li><li>Your <strong>PvPvE matchmaking rating will not be affected</strong> while playing in PvE sessions.</li><li>It’s important to remember that <strong>this is, at least initially, a limited test.</strong> When the test ends, the toggle will be removed and matchmaking will return to normal. Your feedback and data will help to shape the future of this system.</li></ul>"
   },
   {
    "type": "html",
    "en": "<h3>PvE Experience</h3>"
   },
   {
    "type": "html",
    "en": "<p>The PvE experience in this test is one where players can scavenge, complete quests and explore in relative safety from other hostile players. <strong>The intent here is not to test how we can make PvE more challenging or to try new PvE progression, rather it is an attempt to give players an alternative to PvP encounters </strong>- of course we will be listening to what you have to say after the test and what you want from the feature. </p>"
   },
   {
    "type": "html",
    "en": "<p>There are however a few differences in the PvE experience:</p>"
   },
   {
    "type": "html",
    "en": "<ul><li>The overall loot value is lowered to compensate for the relative safety of PvE.</li><li>If you are downed by ARC’s, be a bit careful when crawling, they might re-acquire you as a target even when you are moving when downed. They will ignore you if you stay still. We’re trying this to maintain some tension to compensate for the lack of a PvP threat.</li></ul>"
   },
   {
    "type": "html",
    "en": "<h3>Risks and Balance</h3>"
   },
   {
    "type": "html",
    "en": "<p>It’s important to mention that this is not a risk-free test. The first, unlaunched iteration of ARC Raiders was conceived as a PvE game, and we have been hesitant to return to that concept. There is a risk that introducing a PvE matchmaking toggle could reduce some of the tension that the game was built around. At the same time, we have to respect that some players want to enjoy the game in their own way, and we can’t ignore what the data is telling us. </p>"
   },
   {
    "type": "html",
    "en": "<p>As creators, we design a game with an intention for how we think it should be played; but after launch, it becomes the players’ game. This is one of the unique and wonderful things about making games; we build something with a specific vision,  and then we get to see players finding their own ways to enjoy it.<br></p>"
   },
   {
    "type": "html",
    "en": "<p>Testing the PvE Matchmaking toggle is a way to respect that our players have different needs than what we first envisioned. </p>"
   },
   {
    "type": "html",
    "en": "<p>There are a couple of things we will keep a close eye on:</p>"
   },
   {
    "type": "html",
    "en": "<ul><li><strong>Player economy</strong>: Friendly players, and by extension the PvE sessions, see higher rates of extraction and more value earned. To account for this during the test, PvPvE sessions will have slightly higher baseline loot values.</li><li><strong>Matchmaking and queue times:</strong> In low population regions or during off hours, there might be a small increase in matchmaking times. We will monitor this closely to make sure that we’re providing good sessions for everyone. Depending on how many players try the PvE toggle, it may also might affect the quality of some of the PvPvE sessions, which we will also watch closely and adjust as needed. </li></ul>"
   },
   {
    "type": "html",
    "en": "<h3>Looking Ahead</h3>"
   },
   {
    "type": "html",
    "en": "<p>During the test and after its conclusion we will review the feedback and data we’ve collected to help determine how we move forward. Your feedback will be crucial to that process. <br></p>"
   },
   {
    "type": "html",
    "en": "<p>We want to set a few expectations for what comes next:</p>"
   },
   {
    "type": "html",
    "en": "<ul><li><strong>It’s possible that this will not work. This test is not a promise that there will be a PvE mode in the future</strong>, but take this as an indication that we are seriously considering it.</li><li>We don’t yet know how the potential future version of this setting might look. It’s plausible that any future version could look very different from what you experience in the beta test. We believe this is something that should evolve over time, together with you the players.</li></ul>"
   },
   {
    "type": "html",
    "en": "<p>Our goal is to keep the communication open with you, and we’ll share our findings and future plans sometime after the test. We hope that you participate and share with us what you liked (and disliked!) about the PvE matchmaking test, as well as all the content we have for you in the Frozen Trail update. </p>"
   },
   {
    "type": "html",
    "en": "<p>I’m very excited to meet you Topside and hear what you think!</p>"
   },
   {
    "type": "html",
    "en": "<p>Best,</p>"
   },
   {
    "type": "html",
    "en": "<p>Aleks</p>"
   },
   {
    "type": "html",
    "en": "<p>Executive Producer, ARC Raiders</p>"
   },
   {
    "type": "html",
    "en": "<h3>FAQs</h3>What is the PvE toggle?When is the test happening?Is this a permanent PvE mode?How will PvE matchmaking work?Can I switch between PvE and PvPvE?Will PvE affect my PvPvE matchmaking rating?Will all maps and conditions be available in PvE?Why is Embark testing a PvE option?Does this mean ARC Raiders is becoming a PvE game?Could PvE reduce the tension of ARC Raiders?Will PvE affect the in-game economy?Will the toggle affect matchmaking or queue times?What happens after the test?What if the test doesn’t work?What does Embark want players to do?"
   }
  ]
 },
 {
  "id": "frozen-trail-content-preview",
  "url": "https://arcraiders.com/news/frozen-trail-content-preview",
  "date": "2026-09-23",
  "tags": [],
  "thumb": "https://assets.arcraiders.com/article-cards/2c0b3305-9d3d-first-look-card-600x200-600x200.png",
  "title": {
   "en": "Frozen Trail First Look: Content highlights from October 8"
  },
  "body": [
   {
    "type": "html",
    "en": "<p>Raiders,</p>"
   },
   {
    "type": "html",
    "en": "<p>The Frozen Trail Update is just around the corner. Are you ready to gear up and face whatever is waiting for us beyond the Rust Belt? </p>"
   },
   {
    "type": "html",
    "en": "<p>Ahead of October 8, we wanted to give you a preview of what’s in store. Braving the new frontier will challenge you to your extremes, but you’ll also be offered opportunities to develop your capabilities so you’re prepared for the danger. </p>"
   },
   {
    "type": "html",
    "en": "<p>Here’s a glimpse of the content we have in store for Frozen Trail.</p>"
   },
   {
    "type": "video",
    "id": "GMznEoW78dA",
    "title": "Frozen Trail: First Look | ARC Raiders"
   },
   {
    "type": "html",
    "en": "<h2>New Map: Pendola Pass</h2>"
   },
   {
    "type": "html",
    "en": "<p>With your help, Celeste and Shani have triangulated the source of the strange signal that’s been ringing across Toledo. All signs point toward an old Italian village and Exodus transport hub called Pendola Pass. </p>"
   },
   {
    "type": "html",
    "en": "<p>Beyond the peaks that envelope the Rust Belt, icy air preserves Pendola Pass in its eerie grasp. Classic signs of an old-world civilization punctuate the narrow stretch: a supermarket, and a lifeless town square. Signs of the Exodus Project loom large: the observatory and buried train depot that once served as a major transit hub.</p>"
   },
   {
    "type": "html",
    "en": "<p>But dominating everything else lies the reason Raiders are called to Pendola Pass - one of the Emperors has fallen. Rare technology lies within, and your job is simple - get there, and find a way inside. </p>"
   },
   {
    "type": "html",
    "en": "<p>Between a scrambled ARC response and brutal flash freezes that cut through the valley, the adventure will be dangerous. Are you sure you’re ready for what lies beyond the Rust Belt?</p>"
   },
   {
    "type": "image",
    "html": "<img src=\"https://assets.arcraiders.com/media/2-1-1024x576.png\" alt=\"\" loading=\"lazy\" width=\"1024\" height=\"576\">"
   },
   {
    "type": "html",
    "en": "<h2>Frigate</h2>"
   },
   {
    "type": "html",
    "en": "<p>A fallen Emperor is unprecedented, and ARC are quick to react. They’re sending one of their largest vessels to patrol the area - Raiders have started calling it the Frigate. </p>"
   },
   {
    "type": "html",
    "en": "<p>The Frigate presents a substantial challenge to highly skilled Raiders who, despite the danger, see opportunity within. After finding a way to get on board, you’ll need to navigate its internal passageways, unlock paths, and defend yourself against ARC new and old. </p>"
   },
   {
    "type": "html",
    "en": "<p>But you won’t be alone. Other Raiders have their eyes on the prize, and you’ll be forced to collaborate or cut through them in order to pass. The scale of the challenge may demand a different approach to one you&#x27;re used to - when you’re caught in close quarters hundreds of feet in the air, you’ll have to find a suitable strategy, one way or the other. </p>"
   },
   {
    "type": "html",
    "en": "<h2>New Enemy: Bully</h2>"
   },
   {
    "type": "html",
    "en": "<p>Bully by name, bully by nature: our new machine-learned enemy is an oppressive, aggressive beast that cedes no ground as it gallops upon your position and fights with a host of lethal attacks. Use cover, time your response, and hit your shots; the Bully is quick on its feet and unhinged in its quest.</p>"
   },
   {
    "type": "image",
    "html": "<img src=\"https://assets.arcraiders.com/media/2d6c93ef-e277-AR_Bumper_ARC_Bully_16_9-1024x576.jpg\" alt=\"\" loading=\"lazy\" width=\"1024\" height=\"576\">"
   },
   {
    "type": "html",
    "en": "<h2>New Enemy: Skulker</h2>"
   },
   {
    "type": "html",
    "en": "<p>In contrast to the Bully, the Skulker is opportunistic, lying in wait and skirting the edges of your vision to get the drop and unleash a flurry of blows. This is one you’ll want to keep an eye on as a momentary distraction will see it retreat out of sight - the next time you see it, you’ll be feeling it too. </p>"
   },
   {
    "type": "image",
    "html": "<img src=\"https://assets.arcraiders.com/media/c83fa8f9-0b7d-AR_Bumper_ARC_Skulker_16_9-1024x576.jpg\" alt=\"\" loading=\"lazy\" width=\"1024\" height=\"576\">"
   },
   {
    "type": "html",
    "en": "<h2>New Enemy: Hydra</h2>"
   },
   {
    "type": "html",
    "en": "<p>This enemy may not traverse, but it sure does move. Split into three stacked and autonomous portions, the Hydra is a turret that can handle entire squads with its triple-threat of weaponry. Found upon the Frigate, the Hydra will require a tactical approach in which Raiders divert attention, find cover quickly, and attack rapidly when the moment arises. </p>"
   },
   {
    "type": "image",
    "html": "<img src=\"https://assets.arcraiders.com/media/a6a68676-3b59-AR_Bumper_ARC_Hydra_16_9-1024x576.jpg\" alt=\"\" loading=\"lazy\" width=\"1024\" height=\"576\">"
   },
   {
    "type": "html",
    "en": "<h2>Raider Den Extension: Outpost</h2>"
   },
   {
    "type": "html",
    "en": "<p>Celeste is offering Raiders who heed her call to explore Pendola Pass a home away from home: the Outpost. Nestled between the Rust Belt and the perilous mountain range, the Outpost is the first step to reclaiming parts of the surface. </p>"
   },
   {
    "type": "html",
    "en": "<p>Customize your new home with different modules and embellish the interiors with furniture. Investigate new elements of the world using the Research Workstation which will allow you to access higher levels of weapon customization and modding, preparing you for the journey beyond the mountain. </p>"
   },
   {
    "type": "html",
    "en": "<p>The Outpost is the start of a feature we hope to develop much further, eventually giving players a deeply personal space that allows them to become the Raider they want to be.</p>"
   },
   {
    "type": "image",
    "html": "<img src=\"https://assets.arcraiders.com/media/7a701a7d-8df3-AR_Bumper_Location_Outposts_16_9-1024x576.jpg\" alt=\"\" loading=\"lazy\" width=\"1024\" height=\"576\">"
   },
   {
    "type": "html",
    "en": "<h2>Amplified Weapons</h2>"
   },
   {
    "type": "html",
    "en": "<p>New weapons are great, and Frozen Trail certainly introduces fresh guns for your stash, but we wanted to systemically change how you interact with combat in the late game. We know that highly-skilled Raiders are loyal to their favorite weapons, but that means others barely get used - that’s why we’ve been building an upgrade system that totally reimagines some of the guns you’re already used to. </p>"
   },
   {
    "type": "html",
    "en": "<p>Using the fully-upgraded Research Workstation in your Outpost, Raiders will have the opportunity to access a fifth quality level for a range of guns. This level lets you unlock a branching path of abilities and enhancements to your weapons that can completely change their behavior; imagine a fully-automatic Burletta, a Renegade with a scope, or a Rattler with incendiary bullets and a 64 bullet magazine.</p>"
   },
   {
    "type": "html",
    "en": "<p>The hope is that this feature allows late-game players to reinvent their arsenal and personalize their weapons with high-tier upgrades that set them apart from the crowd. The feature is rolling out to 15 of our weapons, with more planned for the future.</p>"
   },
   {
    "type": "image",
    "html": "<img src=\"https://assets.arcraiders.com/media/3591bdaa-b6f0-AR_Bumper_Amplified-Weapons_16_9-1024x576.jpg\" alt=\"\" loading=\"lazy\" width=\"1024\" height=\"576\">"
   },
   {
    "type": "html",
    "en": "<h2>New Weapon: Stiletto</h2>"
   },
   {
    "type": "html",
    "en": "<p>The Stiletto is a light-ammo battle rifle that fits in as an early-game alternative to the Renegade. Cheap to craft and easy to wield, it’s the perfect choice for Raiders with a steady shot looking to attack from distance. Fire rate can be fast, but button mashing will sacrifice accuracy - keep a cool head and hit your shots. </p>"
   },
   {
    "type": "image",
    "html": "<img src=\"https://assets.arcraiders.com/media/8d30b481-cc19-AR_Bumper_Weapon_Stiletto_16_9-1024x576.jpg\" alt=\"\" loading=\"lazy\" width=\"1024\" height=\"576\">"
   },
   {
    "type": "html",
    "en": "<h2>New Weapon: Bantam</h2>"
   },
   {
    "type": "html",
    "en": "<p>The Bantam is a snub-nosed revolver that uses heavy ammo to punch a hole straight through your adversaries. Effective against ARC and Raiders, the Bantam comes with a unique hip-fire capability to help you live out the cowboy fantasy… even if you’ve got frozen fingers. </p>"
   },
   {
    "type": "image",
    "html": "<img src=\"https://assets.arcraiders.com/media/840002ea-b0ea-AR_Bumper_Weapon_Bantam_16_9-1024x576.jpg\" alt=\"\" loading=\"lazy\" width=\"1024\" height=\"576\">"
   },
   {
    "type": "html",
    "en": "<h2>Grappling Hook</h2>"
   },
   {
    "type": "html",
    "en": "<p>It’s important for us to focus on gadgets and items that offer new ways to play and fresh modes of traversal. That’s where the Grapple Hook comes in, letting you climb hard to reach spots, abseil off buildings, and swing over large gaps. Raiders who get creative will find themselves able to navigate the terrain in totally new ways. </p>"
   },
   {
    "type": "image",
    "html": "<img src=\"https://assets.arcraiders.com/media/d77a737d-0e92-AR_Bumper_Gadgets_GrapplingHook_16_9-1024x576.jpg\" alt=\"\" loading=\"lazy\" width=\"1024\" height=\"576\">"
   },
   {
    "type": "html",
    "en": "<h2>Tethers</h2>"
   },
   {
    "type": "html",
    "en": "<p>As part of our larger system of tethers and constraints, we’ve built two new gadgets that let you trip up your enemies. The Tether Launcher allows you to connect two separate points with a wire, rooting them in place for easy pickings or even attaching Raiders to ARC and watching as they’re dragged away. The Yank Grenade works on the same principle, but when it explodes, it pulls a nearby target with a violent force. This is perfect for smashing flying ARC to the ground or pulling other Raiders out of cover. </p>"
   },
   {
    "type": "image",
    "html": "<img src=\"https://assets.arcraiders.com/media/aa0aa1dc-2c28-AR_Bumper_Gadgets_TetherLauncher_16_9-1024x576.jpg\" alt=\"\" loading=\"lazy\" width=\"1024\" height=\"576\">"
   },
   {
    "type": "html",
    "en": "<h2>Camera</h2>"
   },
   {
    "type": "html",
    "en": "<p>The Rust Belt is home to many DIY photographers and Topside journalists. Using the humble Binoculars, we’ve seen beautiful pictures from your Raids - that’s why we’re introducing a fully-functioning camera gadget. This launches with a range of features including zoom, aperture, manual and automatic focus racking, and even a selfie mode with a range of custom emotes. Pictures will save to your Codex, letting you relive your most triumphant moments from the safety of your home. </p>"
   },
   {
    "type": "image",
    "html": "<img src=\"https://assets.arcraiders.com/media/9e76df9b-694a-Screenshot%202026-09-16%20173735-1024x456.png\" alt=\"\" loading=\"lazy\" width=\"1024\" height=\"456\">"
   },
   {
    "type": "html",
    "en": "<h2>Instruments</h2>"
   },
   {
    "type": "html",
    "en": "<p>Two new instruments can be heard Topside this October, the Harmonica, and the Banjo (Blueprint offered in the Collector Set DLC). Bring the sounds of southern swamps to the Rust Belt this fall - It’s time to get the band back together!</p>"
   },
   {
    "type": "image",
    "html": "<img src=\"https://assets.arcraiders.com/media/9e904fd5-01b4-AR_Bumper_Instrument_Harmonica_16_9-1024x576.jpg\" alt=\"\" loading=\"lazy\" width=\"1024\" height=\"576\">"
   },
   {
    "type": "html",
    "en": "<h2>Weapon Stencils</h2>"
   },
   {
    "type": "html",
    "en": "<p>Re-skin your weapon with a pinch of Raider flair using the new Weapon Stencils coming in the Frozen Trail update! Leave enemies in no doubt who shot them, but beware - Raiders who best you will be more than happy to take your personalized weapon for themselves. </p>"
   },
   {
    "type": "html",
    "en": "<h2>Reward Pass</h2>"
   },
   {
    "type": "html",
    "en": "<p>The Frozen Trail update also launches with a new progression mechanic, the Reward Pass. These passes are an evolution of the Raider Decks, allowing you to try out all of the exciting new items and content from the update.</p>"
   },
   {
    "type": "html",
    "en": "<ul><li>The Free Pass offers a series of rewards unlocked by completing Feats, such as 200 Raider Tokens, five new outfits, new gameplay items, as well as 20 cosmetic items including Scrappy Outfits, Furniture, Charms, Attachments, and Emotes. </li><li>The Premium Pass is designed for Raiders who want to get even more out of the update: this Pass includes premium toggles for all the outfits, exclusive colorways, weapon stencils, hairstyles, and 1,150 Raider Tokens. </li><li>The Legacy Pass is free for all Raiders and combines all our existing Raider Decks, so you won’t lose any existing progress and can still work your way through those rewards.</li></ul>"
   },
   {
    "type": "html",
    "en": "<h2>Collector Set DLC</h2>"
   },
   {
    "type": "html",
    "en": "<p>For those Raiders that want the full Frozen Trail experience, the Collector Set DLC offers all both the free and premium Reward Passes, as well as a new cosmetic set, the Renzo, Dragon’s Breath Weapon Stencil, Bob Hair Style, and 2,400 Raider Tokens.</p>"
   },
   {
    "type": "html",
    "en": "<h2>See you Topside</h2>"
   },
   {
    "type": "html",
    "en": "<p>Join us on October 8 for all this, and more, including new questlines and improvements, a Skill Tree rework including new and improved skills, and a new Map Condition - we’re excited to welcome you to the new frontier. </p>"
   },
   {
    "type": "html",
    "en": "<p>On Friday, September 25, 6pm CEST, we will host a dev Q&amp;A livestream event about the Frozen Trail update. Join us live and submit questions about the First Look event!</p>"
   },
   {
    "type": "html",
    "en": "<p>Gear up. Dress warm. See you Topside.</p>"
   },
   {
    "type": "html",
    "en": "<p>The ARC Raiders Team</p>"
   }
  ]
 },
 {
  "id": "store-update-1-47-0",
  "url": "https://arcraiders.com/news/store-update-1-47-0",
  "date": "2026-09-22",
  "tags": [
   "Store Update",
   "Patch Notes"
  ],
  "thumb": "https://assets.arcraiders.com/article-cards/83d80ad9-8b0f-store-update-1.47-card-600x200-600x200.png",
  "title": {
   "en": "Store Update 1.47.0"
  },
  "body": [
   {
    "type": "image",
    "html": "<img src=\"https://assets.arcraiders.com/media/ed2c29dc-6dce-ARC-Raiders_Steam_EventHeader_StoreUpdate_1920x622%20(2)-1024x332.jpg\" alt=\"\" loading=\"lazy\" width=\"1024\" height=\"332\">"
   },
   {
    "type": "html",
    "en": "<p>Hey there, Raiders! <br><br>Update 1.47.0 is underway, bringing two new color variants for the Riposta Set, an update on Fair Play &amp; a few more fixes &amp; improvements. A download is required, so make sure you do that before loading back in.</p>"
   },
   {
    "type": "html",
    "en": "<h2>Highlights:</h2>"
   },
   {
    "type": "html",
    "en": "<ul><li>Frozen Trail - First Look coming September 23rd!</li><li>New Camo &amp; White variants for the Riposta Set</li><li>An update on our ongoing Fair Play efforts</li><li>Fixes for the Rawhide Outfit, Keyboard Input issues and the occasional invisible door</li><li>Expedition 5 Sign-Up Reminder</li></ul>"
   },
   {
    "type": "html",
    "en": "<h2>Frozen Trail is coming - tune in for a First Look!</h2>"
   },
   {
    "type": "html",
    "en": "<p><a href=\"https://x.com/ARCRaidersGame/status/2100978160364146717\" target=\"_blank\" rel=\"noopener\">In case you missed it</a>, we’ll be holding a First Look at Frozen Trail and what’s coming with the update <em>tomorrow!</em> <strong>On September 23rd, at 10am PDT (7pm CEST)</strong>, tune in for an extended peek at our biggest update yet.<br><br>Can’t wait to hear what you think! We’ve got more planned ahead of October 8th, stay tuned.</p>"
   },
   {
    "type": "html",
    "en": "<h2>Content and Bug Fixes </h2>"
   },
   {
    "type": "html",
    "en": "<h3>Cosmetic</h3>"
   },
   {
    "type": "html",
    "en": "<ul><li>Fixed an issue where the Rawhide outfit’s headgear would remain on when toggled off in Customization.</li></ul>"
   },
   {
    "type": "html",
    "en": "<h3>Gameplay</h3>"
   },
   {
    "type": "html",
    "en": "<ul><li>Door blockers will no longer create a copy of their mesh on the opposite side from the direction they are applied.</li><li>Fixed an issue where keyboard input could stop working after launching unfocused or returning from background, ensuring keyboard controls reliably respond when refocusing the window.</li><li>Fixed an issue where doors could become out of sync in some cases, making them appear open to the player whilst actually being closed.</li><li>Fixed an issue where swapping or splitting items could place them into incompatible containers (such as forcing non-quick-use items into the belt), and added safeguards against invalid inventory slot indexing in the inventory.</li></ul>"
   },
   {
    "type": "html",
    "en": "<h3>Maps</h3>"
   },
   {
    "type": "html",
    "en": "<h4>Buried City</h4>"
   },
   {
    "type": "html",
    "en": "<ul><li>Fixed an issue where lighting in Buried City could appear overly dark or missing, improving overall visibility.</li></ul>"
   },
   {
    "type": "html",
    "en": "<h4>Riven Tides</h4>"
   },
   {
    "type": "html",
    "en": "<ul><li>Fixed visual issues that could appear while traversing Riven Tides.</li></ul>"
   },
   {
    "type": "html",
    "en": "<h4>General</h4>"
   },
   {
    "type": "html",
    "en": "<ul><li>Fixed an issue where objects in the world displayed incorrect colors, restoring items like red lockers, toolboxes, office chairs, cars, chests, and shipping containers to their intended appearance.</li></ul>"
   },
   {
    "type": "html",
    "en": "<h3>Performance</h3>"
   },
   {
    "type": "html",
    "en": "<ul><li>Fixed an issue where item tooltips in the inventory could keep data from previous screens, increasing memory use over time and affecting stability after long play sessions.</li></ul>"
   },
   {
    "type": "html",
    "en": "<h3>Stability</h3>"
   },
   {
    "type": "html",
    "en": "<ul><li>Improved crash detection &amp; diagnostics tools.</li><li>Fixed a rare crash that could occur during server shutdown, improving overall stability.</li><li>Fixed an Xbox issue that could cause resource conflicts.</li></ul>"
   },
   {
    "type": "html",
    "en": "<h4>PS5</h4>"
   },
   {
    "type": "html",
    "en": "<ul><li>Addressed a frequent crash on PS5 related to the physics engine.</li></ul>"
   },
   {
    "type": "html",
    "en": "<h4>Inventory</h4>"
   },
   {
    "type": "html",
    "en": "<ul><li>Improved stability when opening the Inventory screen.</li></ul>"
   },
   {
    "type": "html",
    "en": "<h3>UI</h3>"
   },
   {
    "type": "html",
    "en": "<h4>Expedition</h4>"
   },
   {
    "type": "html",
    "en": "<ul><li>The Expedition Project button now indicates when an Expedition is paused after the cutoff date and prevents committing resources.</li></ul>"
   },
   {
    "type": "html",
    "en": "<h4>Skill Tree</h4>"
   },
   {
    "type": "html",
    "en": "<ul><li>Changed Skill Point assignment to hold-to-assign by default in the Skill Tree.</li></ul>"
   },
   {
    "type": "html",
    "en": "<h2>A Quick Update on Fair Play Efforts</h2>"
   },
   {
    "type": "html",
    "en": "<p>While our dev team is hard at work putting the finishing touches on Frozen Trail, our Anti-Cheat team is making constant updates and improvements across the board to our Fair Play initiatives.</p>"
   },
   {
    "type": "html",
    "en": "<p>When it comes to economy-related manipulation, there have been several ban waves for accounts we detected exhibiting &quot;bot-like&quot; behavior. We’ll continue to track and refine our detection to cover broader types of suspect behavior (such as XP farming) in the future, as well. We also continue sanctioning abnormally high-value item transfers. Item duplication is also on our minds, and we’re seeing positive outcomes following this summer’s ongoing improvements on that front.</p>"
   },
   {
    "type": "html",
    "en": "<p>We are constantly working on ways to prevent serial cheaters and discourage them from returning. Currently, we&#x27;re strengthening our policies when it comes to shared licenses and how those are restricted when an account is sanctioned. In practice, this will make it harder for cheaters who were detected on one account to purchase another. Keeping track of a cheater&#x27;s behavior before and after receiving a sanction helps us anticipate it and act faster in the future.</p>"
   },
   {
    "type": "html",
    "en": "<p>Previously, we mentioned the speed of action against unfair play is important to us. To that end, we have been improving our detection systems and we are extending first-strike permanent bans. This allows us to catch offenders much quicker with a very high degree of confidence.</p>"
   },
   {
    "type": "html",
    "en": "<p>While we keep improving and expanding the ways we keep Topside fair, we want to thank you for helping us do that by reporting players and sharing any illicit behavior with us.</p>"
   },
   {
    "type": "html",
    "en": "<h2>Reminder - Claim your Rubber Ducks!</h2>"
   },
   {
    "type": "image",
    "html": "<img src=\"https://assets.arcraiders.com/media/270045c6-e0ab-duck2-1024x251.jpg\" alt=\"\" loading=\"lazy\" width=\"1024\" height=\"251\">"
   },
   {
    "type": "html",
    "en": "<p>Heads up! After <strong>October 8th</strong>, the inbox message that contains the community-made Rubber Ducks will no longer be sent out. <strong>Make sure to log in and claim them before that deadline. </strong><br><br>Wouldn’t wanna miss out on those awesome ducks!</p>"
   },
   {
    "type": "html",
    "en": "<h2>Expedition 5 - Departure Window closes September 29th</h2>"
   },
   {
    "type": "html",
    "en": "<p>Make sure to finish up your Expedition project <em>and</em> sign up for Departure before September 29th 10am CEST/8am UTC/1am PT. <br><br>There is <strong>no Last Call</strong> this time around, so be mindful of that!<br></p>"
   },
   {
    "type": "html",
    "en": "<p>We know that a few of you are having issues with the Departure screen. If you are experiencing issues confirming your sign-up for departure, please reach out to support as soon as possible. You can do so <a href=\"https://id.embark.games/id/sign-in\" target=\"_blank\" rel=\"noopener\">here</a>.</p>"
   },
   {
    "type": "html",
    "en": "<h2>Known Issues</h2>"
   },
   {
    "type": "html",
    "en": "<ul><li>We are deploying multiple stability improvements targeting Xbox Series X|S crashes. Please report any persistent issues to help guide further fixes. </li><li>There are future improvements in the works for the Quick Wheel’s behavior to prevent inaccurate switching or “jumping” from one item slot to the other.</li><li>The weapon swap animation may appear broken if weapon swapping right after vaulting.</li><li>Player animations may appear broken when interrupting a search of the Baron Husk.</li><li>Shredders float to the ceiling in some rooms of the Hidden Bunker.</li><li>Leapers can jump through the ARC Turbine.</li><li>Shots taken while riding ARC may not register correctly.</li><li>The player&#x27;s character may stutter / jitter after being revived.</li><li>The Matriarch may occasionally not use all of its ranged attacks.</li><li>The player&#x27;s footsteps are inaudible during constant shoulder swap while sprinting.</li><li>Players can sometimes get stuck on obstacles while sliding downhill.</li><li>When using keyboard layouts other than US English, custom keybindings reset after every raid.</li><li>In some instances, long lists of text can disappear when scrolling through them.</li></ul>"
   },
   {
    "type": "html",
    "en": "<p><br>See you soon!<br>//Raz</p>"
   }
  ]
 },
 {
  "id": "store-update-1-46-0",
  "url": "https://arcraiders.com/news/store-update-1-46-0",
  "date": "2026-09-15",
  "tags": [
   "Store Update"
  ],
  "thumb": "https://assets.arcraiders.com/article-cards/09ccc2ff-c2cb-store-update-1.46-card-600x200-600x200.png",
  "title": {
   "en": "Store Update 1.46.0"
  },
  "body": [
   {
    "type": "image",
    "html": "<img src=\"https://assets.arcraiders.com/media/92dab6d2-6f6c-ARC-Raiders_Blog_EventHeader_StoreUpdate_1920x622%20(4)-1024x332.jpg\" alt=\"\" loading=\"lazy\" width=\"1024\" height=\"332\">"
   },
   {
    "type": "html",
    "en": "<p>Raiders!</p>"
   },
   {
    "type": "html",
    "en": "<p>Store Update 1.46.0 is going live right now with two new colour variants for the Boonie Set (Black and Green Camo), if you already own the outfit they&#x27;ll be unlocked for you automatically. No restart needed!</p>"
   },
   {
    "type": "html",
    "en": "<h2><strong>Ascending the Mountain </strong></h2>"
   },
   {
    "type": "html",
    "en": "<p>Ferrovian engineers continue to work on Apollo&#x27;s ongoing experimental transportation project, supported by the invaluable supplies provided by the Raiders.</p>"
   },
   {
    "type": "html",
    "en": "<p>Lance is making a killing selling medical supplies due to all the... misfires.</p>"
   },
   {
    "type": "html",
    "en": "<p>Keep an eye out for progress, we may be getting closer to a first look at the frigid peaks than you think!</p>"
   },
   {
    "type": "html",
    "en": "<h2><strong>Trials Season 5: One Last Push</strong></h2>"
   },
   {
    "type": "html",
    "en": "<p>This is your final week of Trials Season 5, you&#x27;ve got until September 22 to climb the ranks! Now’s the time to rally your crew, dust off your gear, and make one last push to earn yourself the Scorta Set.</p>"
   },
   {
    "type": "html",
    "en": "<p>For your final week, the Trials are putting you up against some of the biggest threats you’ll find Topside: Queens and Matriarchs. They’re tough, they’re deadly, and they’re not known to hand out points freely.</p>"
   },
   {
    "type": "image",
    "html": "<img src=\"https://assets.arcraiders.com/media/6e33f558-68ca-ArcRaiders_ScreenShot_16x9_TrialsSeason05-1024x576.jpg\" alt=\"\" loading=\"lazy\" width=\"1024\" height=\"576\">"
   },
   {
    "type": "html",
    "en": "<p>See you Topside,<br>//Ossen</p>"
   }
  ]
 },
 {
  "id": "live-update-1-45-0",
  "url": "https://arcraiders.com/news/live-update-1-45-0",
  "date": "2026-09-08",
  "tags": [
   "Patch Notes"
  ],
  "thumb": "https://assets.arcraiders.com/article-cards/708ee0b9-a1e2-store-update-1.45-card-600x200-600x200.png",
  "title": {
   "en": "Live Update 1.45.0"
  },
  "body": [
   {
    "type": "image",
    "html": "<img src=\"https://assets.arcraiders.com/media/ab1dc116-b67b-ARC-Raiders_Blog_EventHeader_LiveUpdate_1920x622-1024x332.jpg\" alt=\"\" loading=\"lazy\" width=\"1024\" height=\"332\">"
   },
   {
    "type": "html",
    "en": "<p>Raiders!</p>"
   },
   {
    "type": "html",
    "en": "<p>Update 1.45.0 is going live right now and with it a number of fixes, a new Raider Project, the start of the fifth Expedition, the Hornet Hunter Set and changes coming to Cred. Make sure to restart the game to get the download.</p>"
   },
   {
    "type": "html",
    "en": "<p>This will be our last Live Update before October 8, but we won&#x27;t be going quiet in the meantime, a smaller update is still planned before then!</p>"
   },
   {
    "type": "html",
    "en": "<h2><strong>HIGHLIGHTS</strong></h2>"
   },
   {
    "type": "html",
    "en": "<ul><li>Raider Project: Ascending the Mountain</li><li>The Hornet Hunter Set</li><li>Cred Expiration</li><li>Expedition 5</li><li>Community Rubber Ducks</li></ul>"
   },
   {
    "type": "html",
    "en": "<h2><strong>Forging the Way North</strong></h2>"
   },
   {
    "type": "html",
    "en": "<p>Raider efforts have revealed clues to the mystery of phantom ARC signals that have Shani concerned. Unfortunately, these signals lead ARC to a place we can’t follow -  the mountain range just beyond the reach of our Tube system. Rumor has it Apollo’s working on an experimental solution, and he’s requested assistance from Raiders who understand schematics, and can keep their heads down.</p>"
   },
   {
    "type": "image",
    "html": "<img src=\"https://assets.arcraiders.com/media/c0d3f2f8-6b9e-ArcRaiders_ScreenShot_16x9_Narrative_01-1024x576.jpg\" alt=\"\" loading=\"lazy\" width=\"1024\" height=\"576\">"
   },
   {
    "type": "html",
    "en": "<h2><strong>Cred Expiration</strong></h2>"
   },
   {
    "type": "html",
    "en": "<p>As we look ahead to Frozen Trail and a rework to Raider Decks, we’ll be making changes to the Cred currency. It will remain usable until October 8, so be sure to use any remaining Cred before then. </p>"
   },
   {
    "type": "html",
    "en": "<p>We are retiring Cred as a currency, as we’ll be introducing a more expansive reward system launching with the Frozen Trail Update. All existing Raider Deck rewards will also be available in the new system. You will keep any rewards you have already claimed at the time of the update.</p>"
   },
   {
    "type": "html",
    "en": "<p>Any Cred remaining on your account will expire with the Frozen Trail update, so please be sure to spend your Cred with Shani or on any remaining Raider Deck rewards.</p>"
   },
   {
    "type": "html",
    "en": "<h2><strong>Community Rubber Ducks</strong></h2>"
   },
   {
    "type": "html",
    "en": "<p>The community designed duckies that you have selected have finally made their way into the game! Head on over to Bird City and display them proudly in your Raider Den! </p>"
   },
   {
    "type": "html",
    "en": "<p>Again, huge congratulations to the designers: <em>gekko.rar, im_AshCheeks and nassguhl!</em></p>"
   },
   {
    "type": "image",
    "html": "<img src=\"https://assets.arcraiders.com/media/2cf42228-8c79-ArcRaiders_ScreenShot_Master_16_9_Duckies-1024x576.jpg\" alt=\"\" loading=\"lazy\" width=\"1024\" height=\"576\">"
   },
   {
    "type": "html",
    "en": "<h2></h2>"
   },
   {
    "type": "html",
    "en": "<h2><strong>Content and Bug Fixes</strong></h2>"
   },
   {
    "type": "html",
    "en": "<h3>ARC</h3>"
   },
   {
    "type": "html",
    "en": "<ul><li>Snitch Scanners will now spawn ARC similarly to the regular Snitch, but with a lower chance for stronger ARC.</li></ul>"
   },
   {
    "type": "html",
    "en": "<h3>Audio</h3>"
   },
   {
    "type": "html",
    "en": "<ul><li>Fixed an issue where the Equalizer could play its firing sound effect when holstering.</li><li>Fixed an issue where voice chat did not work when Raider Voice was enabled.<br></li></ul>"
   },
   {
    "type": "html",
    "en": "<h3>Customization</h3>"
   },
   {
    "type": "html",
    "en": "<ul><li>The Boonie outfit will be available from September 15th.</li></ul>"
   },
   {
    "type": "html",
    "en": "<h3>Gameplay</h3>"
   },
   {
    "type": "html",
    "en": "<ul><li>Landing on moving surfaces will now make you follow that surface when landing, not while still in the air.</li><li>You can now rebind quick item cycling separately from the quick-use wheel (or disable cycling), and you may bind both to the same key. This helps prevent unintended item swaps after closing the wheel.</li><li>Fixed an issue where ARC Turbine mines could not be pinged.</li><li>Reduced weapon sway for Aphelion to improve aiming stability.</li><li>Starting an Expedition no longer resets your quests by default; you can now choose whether to reset them when departing.</li><li>Fixed an issue where the Matriarch’s stomp could damage players through tall cover or when standing on top of the Matriarch.</li></ul>"
   },
   {
    "type": "html",
    "en": "<h3>Stability</h3>"
   },
   {
    "type": "html",
    "en": "<ul><li>Fixed a crash on PS5 that could occur shortly after starting a session.</li><li>Fixed a crash that could occur when rapidly pressing certain keys during gameplay.</li><li>Fixed cases where a squad could become stuck after a squadmate signed out and rejoined, blocking ready-up and preventing matchmaking from starting.</li></ul>"
   },
   {
    "type": "html",
    "en": "<h3>Performance</h3>"
   },
   {
    "type": "html",
    "en": "<ul><li>Upgraded Unreal Engine from 5.3 to 5.7.</li></ul>"
   },
   {
    "type": "html",
    "en": "<h3>UI</h3>"
   },
   {
    "type": "html",
    "en": "<ul><li>The UI indicator showing the current weight of your loadout is now updated directly when dropping parts of a stack.</li><li>Added visual tweaks to selected nodes in the Skill Tree.</li><li>Fixed an issue where some distance based map markers didn&#x27;t appear correctly.</li><li>The pick up prompt will now show “loadout full” while trying to pick up an item with a full inventory.</li><li>Improved matchmaking error messaging: you’ll now see clearer explanations if you go offline while queuing or if your crossplay settings are incompatible, helping diagnose failed matchmaking attempts.</li></ul>"
   },
   {
    "type": "image",
    "html": "<img src=\"https://assets.arcraiders.com/media/a4b678dd-0879-ArcRaiders_ScreenShot_16x9_Project-1024x576.jpg\" alt=\"\" loading=\"lazy\" width=\"1024\" height=\"576\">"
   },
   {
    "type": "html",
    "en": "<h2><strong>KNOWN ISSUES</strong></h2>"
   },
   {
    "type": "html",
    "en": "<ul><li>The second part of the Phantom Targets project could not be started for some players. We will be sending out compensation in a future update.</li><li>There are multiple stability improvements targeting Xbox Series S crashes. Please report any persistent issues to help guide further fixes. </li><li>We’re aware of issues with crashing on PC, related to Windows Update KB5121003. Please consult our <a href=\"https://discord.com/channels/1107589599045361695/1107613897357275188/1537853764193624105\" target=\"_blank\" rel=\"noopener\">workaround shared here</a> while we work on a fix.</li><li>Players on Epic may experience a sudden loss of keyboard input.</li><li><ul><li>While we look into this, we recommend disabling any Overlay you may have active. Additionally, you can try alt-tabbing out and back into the game.</li></ul></li><li>The Rawhide headgear stays on with the toggle set to off.</li><li>The throw animation may sometimes fail to play when attempting to detonate a Trigger ‘Nade immediately after throwing it.</li><li>The weapon swap animation may appear broken if weapon swapping right after vaulting.</li><li>Player animations may appear broken when interrupting a search of the Baron Husk.</li><li>Shredders float to the ceiling in some rooms of the Hidden Bunker.</li><li>Leapers can jump through the ARC Turbine.</li><li>Shots taken while riding ARC may not register correctly.</li><li>Some doors may allow player flashlights’ beams to pass through instead of blocking the emitted light.</li><li>We are aware of some clipping issues with the Triumph, Reaver and Azimuth outfits.</li></ul>"
   },
   {
    "type": "html",
    "en": "<p>See you Topside,<br>//Ossen</p>"
   }
  ]
 },
 {
  "id": "store-update-1-44-0",
  "url": "https://arcraiders.com/news/store-update-1-44-0",
  "date": "2026-09-01",
  "tags": [
   "Store Update"
  ],
  "thumb": "https://assets.arcraiders.com/article-cards/8719da3d-4da0-store-update-1.44-card-300x100-300x100.png",
  "title": {
   "en": "Store Update 1.44.0"
  },
  "body": [
   {
    "type": "image",
    "html": "<img src=\"https://assets.arcraiders.com/media/2c21c7cf-f8ef-ARC-Raiders_Blog_EventHeader_StoreUpdate_1920x622%20(3)-1024x332.jpg\" alt=\"\" loading=\"lazy\" width=\"1024\" height=\"332\">"
   },
   {
    "type": "html",
    "en": "<p>Raiders!</p>"
   },
   {
    "type": "html",
    "en": "<p>Store Update 1.44.0 is going live right now with the stunning Static Set. No restart needed!</p>"
   },
   {
    "type": "html",
    "en": "<p>Gamescom is officially behind us, so Raz and I are settling back into our regular schedule. Meeting so many of you at the booth was honestly the highlight, thanks for coming by! </p>"
   },
   {
    "type": "html",
    "en": "<p>UPDATE: We&#x27;ve just deployed a hotfix to temporarily remove the Static and Cavalier sets from the store and customization screens while we adjust some minor visual elements. They will be re-added as soon as possible. Additionally, &quot;Shotgun Parts&quot; will no longer be available in Ermal&#x27;s shop.</p>"
   },
   {
    "type": "html",
    "en": "<p>See you Topside,<br>//Ossen</p>"
   }
  ]
 },
 {
  "id": "store-update-1-43-0",
  "url": "https://arcraiders.com/news/store-update-1-43-0",
  "date": "2026-08-25",
  "tags": [
   "Store Update"
  ],
  "thumb": "https://assets.arcraiders.com/article-cards/0b922c8b-8406-store-update-1.43-card-300x100-300x100.png",
  "title": {
   "en": "Store Update 1.43.0"
  },
  "body": [
   {
    "type": "image",
    "html": "<img src=\"https://assets.arcraiders.com/media/5e256021-afd6-ARC-Raiders_Steam_EventHeader_StoreUpdate_1920x622-1024x332.jpg\" alt=\"\" loading=\"lazy\" width=\"1024\" height=\"332\">"
   },
   {
    "type": "html",
    "en": "<p>It’s Tuesday, Raiders!</p>"
   },
   {
    "type": "html",
    "en": "<p>Store Update 1.43.0 is rolling out now, introducing the heavy duty Roamer Set! Make sure to restart your game to get the latest version.</p>"
   },
   {
    "type": "html",
    "en": "<h4><strong>Phantom Targets Event - Earn the Anomalia Outfit</strong></h4>"
   },
   {
    "type": "html",
    "en": "<p>Shani’s investigation into the strange ARC behavior is ongoing…</p>"
   },
   {
    "type": "html",
    "en": "<p>The Phantom Targets Event is live till <strong>September 06</strong>, get out there and hunt down those erratic Wasps for their strange glitched tech.</p>"
   },
   {
    "type": "html",
    "en": "<p>Knowledge is key to survival, we need to find out what they’re doing, and fast.<br>You’ll earn the Anomalia Outfit for your contribution to the research effort, alongside the Finger Guns Wave emote, Trashpile Bag, and Raider Tokens to get you appropriately dripped up for what’s on the horizon…</p>"
   },
   {
    "type": "image",
    "html": "<img src=\"https://assets.arcraiders.com/media/cf8183a7-6685-unnamed-1024x576.png\" alt=\"\" loading=\"lazy\" width=\"1024\" height=\"576\">"
   },
   {
    "type": "html",
    "en": "<h4><strong>Anti-Cheat &amp; Linked Accounts</strong></h4>"
   },
   {
    "type": "html",
    "en": "<p>As we continue ramping up on our anti-cheat efforts, we are doubling down on linked accounts. If someone gets access to your account, either with your permission or not, and they&#x27;re caught cheating, your account can be banned even though you weren&#x27;t the one cheating.</p>"
   },
   {
    "type": "html",
    "en": "<p>In order to make sure this does not happen, now is a good time to make sure your account is properly secured via your login provider (Steam, Sony, Xbox, Epic, etc.):</p>"
   },
   {
    "type": "html",
    "en": "<ul><li>Use a strong, unique password</li><li>Enable two-factor authentication</li><li>Never share your login details with anyone</li></ul>"
   },
   {
    "type": "html",
    "en": "<p>Keeping your account secure helps protect your progress and keeps the game fair for everyone. Thanks for helping us in our fight to keep ARC Raiders a great experience for all Raiders.</p>"
   },
   {
    "type": "html",
    "en": "<h4><strong>Wasp Week Community Highlights</strong></h4>"
   },
   {
    "type": "html",
    "en": "<p>Submissions for the special Waspy Community Highlights episode are still open!<br>If you&#x27;ve caught a ride surfing a Wasp through the air, used a Snap Hook to pull one into the ground, or angered the swarm by spamming Snitch Scanners, send us your best videos!</p>"
   },
   {
    "type": "html",
    "en": "<p>We&#x27;ll pick the top 5 to feature in this Community Highlights episode, and win the Wasp Hunter DLC set! </p>"
   },
   {
    "type": "html",
    "en": "<p>Send us your clips here: <a href=\"https://forms.gle/sZmpGBaPhbVAKYrX7\" target=\"_blank\" rel=\"noopener\">https://forms.gle/sZmpGBaPhbVAKYrX7</a> </p>"
   },
   {
    "type": "html",
    "en": "<h4><strong>We&#x27;re at Gamescom! - August 26 - 30</strong></h4>"
   },
   {
    "type": "html",
    "en": "<p>The ARC Raiders team is heading Topside to Gamescom this week. We’re loading the shuttles with merch and coaxing Scrappy into his travel carrier as we write this. Swing by the booth to say hi and scavenge some freebies!</p>"
   },
   {
    "type": "html",
    "en": "<p>See you at the booth or online!</p>"
   }
  ]
 },
 {
  "id": "the-5th-expedition",
  "url": "https://arcraiders.com/news/the-5th-expedition",
  "date": "2026-08-21",
  "tags": [],
  "thumb": "https://assets.arcraiders.com/article-cards/14d605cc-af1e-expedition-5-blog-card-300x100-300x100.png",
  "title": {
   "en": "The 5th Expedition"
  },
  "body": [
   {
    "type": "html",
    "en": "<p>The fifth Expedition window is fast approaching, and with it come a few changes. Based on your feedback, in upcoming Expeditions you’ll be able to opt out of resetting your quest progress, the departure window will be extended by one week, and there won’t be the last call feature this time around.<br>Additionally, we will be pausing Expeditions for a short while to dig deeper into the core systems and make them feel more rewarding and fun!</p>"
   },
   {
    "type": "html",
    "en": "<h2><strong>TIMING</strong></h2>"
   },
   {
    "type": "html",
    "en": "<p>Expedition Window<strong> </strong>opens on<strong> </strong>September 8, 1pm CEST/11am UTC/4am PT, and closes September 29 10am CEST/8am UTC/1am PT.</p>"
   },
   {
    "type": "html",
    "en": "<p>As with all previous Expeditions, completing your Caravan does not count as signing up for the Expedition, you still have to sign up during the window and this time around there is no ‘last call’ feature.</p>"
   },
   {
    "type": "html",
    "en": "<p>Expeditions are a personal progression that players complete in order. The Caravan can be completed in between Expedition windows but finishing the Expedition can only be done during the scheduled Expedition window.</p>"
   },
   {
    "type": "html",
    "en": "<h2><strong>HOW TO DO THE EXPEDITION</strong></h2>"
   },
   {
    "type": "html",
    "en": "<ol><li><strong>Complete the Caravan</strong><br>The option to contribute to the Caravan starts as soon as you complete the previous Expedition and if this is your first Expedition, you can start contributing right away.</li><li><strong>Wait for the Expedition Window</strong><br>The next window opens on September 8, 1pm CEST/11am UTC/4am PT, and closes on September 29, 10am CEST/8am UTC/1am PT.</li><li><strong>Sign Up</strong><br>Once the Expedition window opens, you need to sign up.</li><li><strong>Complete the Challenge</strong><br>In order to get the rewards, players will need to complete a challenge within the Expedition Window (more details below).</li><li><strong>Catch Up</strong><br>Catch up on missed skill points (max 5 per Expedition) for players on their second, third or fourth Expedition (more details below).</li><li><strong>Depart</strong><br>Everyone that signed up departs on September 29.</li><li><strong>No Last Call</strong><br>Make sure to sign up for departure during the window.</li></ol>"
   },
   {
    "type": "html",
    "en": "<h2><strong>WHAT’S NEW</strong></h2>"
   },
   {
    "type": "html",
    "en": "<ul><li><strong>Opt-in Quest reset</strong></li><li><ul><li>We have seen your feedback about the quest line feeling repetitive after every Expedition. To address this, we want to give you the option not to reset your quests and keep your progress so you can continue from where you left off. Since the Hullcracker Blueprint can only be obtained through the quest line, we will give you other ways to get it.</li></ul></li><li><strong>No Last Call</strong></li><li><ul><li>Make sure to sign up during the departure window so you don’t miss out on the Expedition.</li></ul></li><li>The expedition window is <strong>extended</strong> from two to three weeks.</li></ul>"
   },
   {
    "type": "image",
    "html": "<img src=\"https://assets.arcraiders.com/media/a635bda4-86ba-ARCRaiders_Expeditions%20Infographic_05-Approved-1024x576.png\" alt=\"\" loading=\"lazy\" width=\"1024\" height=\"576\">"
   },
   {
    "type": "html",
    "en": "<h2><strong>REWARDS</strong></h2>"
   },
   {
    "type": "html",
    "en": "<ul><li>The complete Zenith Outfit</li><li><a href=\"https://arcraiders.com/news/the-fourth-expedition#mystery-rewards\" target=\"_blank\" rel=\"noopener\">Mystery Rewards</a></li><li>+12 stash space, maxed out at 60</li><li>Skill points:</li><li><ul><li>The bonus skill points from Expeditions cap at 15. Players can still catch-up on previously missed skill points and it’s still tied to stash value. Catch-up for skill points becomes available with your second Expedition and once you get all the maximum 15 skill points, the catch-up is no longer available.</li></ul></li><li>Consecutive buffs: </li><li><ul><li>The XP boost, Scrappy materials boost and repair value increase capped at three levels.</li></ul></li></ul>"
   },
   {
    "type": "html",
    "en": "<h2><strong>Trials</strong></h2>"
   },
   {
    "type": "html",
    "en": "<p>The season currently ongoing will end on September 22, and after that Trials will be on pause for two weeks until October 8.</p>"
   },
   {
    "type": "html",
    "en": "<h2><strong>FUTURE EXPEDITIONS</strong></h2>"
   },
   {
    "type": "html",
    "en": "<p>We have been carefully reviewing your feedback on Expeditions, and while we&#x27;ve made ongoing improvements along the way, we&#x27;ve come to realize that some of the issues you&#x27;ve raised, like the tight departure windows, the reward structure, and accessibility for new players, need more than incremental fixes. They call for bigger changes.</p>"
   },
   {
    "type": "html",
    "en": "<p>In order to address those concerns, we need to pause the Expeditions for a while. The fifth Expedition will be the last one until early 2027, when Expeditions will return with major improvements, tackling some of the biggest player pain points. So, if you’ve been on the fence about departing - now is the time! We will share more details on what those changes will look like in September.</p>"
   },
   {
    "type": "html",
    "en": "<p>During the pause period, any of the consecutive buffs you have earned will persist so no progress is lost. If you have completed all five Expeditions, the Zenith Outfit will be fully unlocked. Also, since Caravans will be reset, any partially completed Caravans will be replaced with Ermal Vouchers of equal value which can be used to purchase Ermal offers together with ARC Parts and firearms trade, or sold for Coin.<br><br>As always, keep the feedback coming. Let us know what you think, and we will continue to make improvements.</p>"
   },
   {
    "type": "html",
    "en": "<p>The ARC Raiders Team</p>"
   }
  ]
 },
 {
  "id": "subway-arc-raiders-partnership",
  "url": "https://arcraiders.com/news/subway-arc-raiders-partnership",
  "date": "2026-08-20",
  "tags": [],
  "thumb": "https://assets.arcraiders.com/article-cards/8f78db08-9682-subway-card-300x100-300x100.png",
  "title": {
   "en": "ARC Raiders x Subway: Exclusive Subterranean outfit"
  },
  "body": [
   {
    "type": "image",
    "html": "<img src=\"https://assets.arcraiders.com/media/8c69d591-d5f8-ARC-Raiders_Steam_EventHeader_1920x622-1024x332.jpg\" alt=\"\" loading=\"lazy\" width=\"1024\" height=\"332\">"
   },
   {
    "type": "html",
    "en": "<h3>Never Raid Hungry</h3>"
   },
   {
    "type": "html",
    "en": "<p>Has this ever happened to you? You load into a map sporting your best gear. You pack plenty of ammo. You’re about to check the map… then you hear it. A deep, sinister growl. Your body trembles. Is a Matriarch on patrol? Did Lance sell you expired stims again? </p>"
   },
   {
    "type": "html",
    "en": "<p>No. You forgot the Raider’s golden rule: <em>“Never go Topside on an empty stomach!”</em></p>"
   },
   {
    "type": "html",
    "en": "<p>ARC Raiders has teamed up with Subway® for a limited time chance to unlock exclusive in-game rewards!</p>"
   },
   {
    "type": "image",
    "html": "<img src=\"https://assets.arcraiders.com/media/04c5c270-3021-ArcRaiders_ScreenShot_Subway_16x9_02-1024x576.jpg\" alt=\"\" loading=\"lazy\" width=\"1024\" height=\"576\">"
   },
   {
    "type": "html",
    "en": "<h3>How to participate</h3>"
   },
   {
    "type": "html",
    "en": "<p>From Aug 20 through Oct 26, raiders can earn in-game rewards by purchasing any qualifying Subway® meal*. This offer is available only at participating US Subway locations, through the Subway app, or <a href=\"http://subway.com/\" target=\"_blank\" rel=\"noopener\">Subway.com</a>. </p>"
   },
   {
    "type": "html",
    "en": "<p>Participants will receive a unique single-use code to unlock the exclusive Subterranean outfit, one of three potential Subway-themed outfit variants, plus two bonus in-game items which rotate weekly throughout the promotion. Codes can be redeemed on PlayStation, Xbox, or PC.</p>"
   },
   {
    "type": "image",
    "html": "<img src=\"https://assets.arcraiders.com/media/627f108c-4078-ArcRaiders_ScreenShot_Subway_16x9_04-1024x576.jpg\" alt=\"\" loading=\"lazy\" width=\"1024\" height=\"576\">"
   },
   {
    "type": "html",
    "en": "<p>To see full details, each week&#x27;s new rewards bundle, and redeem codes, visit the official program site at <a href=\"http://arcraiders.com/subway\" target=\"_blank\" rel=\"noopener\">arcraiders.com/subway</a> or the Subway app.</p>"
   },
   {
    "type": "html",
    "en": "<hr>"
   },
   {
    "type": "html",
    "en": "<p><em>At participating U.S. restaurants. Offer opt-in required. One (1) ARC Raiders Code (the “Code(s)”) with qualifying Subway® meal purchase (excludes Kids Meals). Limit: one (1) Code per order. Valid 8/20/26 – 10/26/26 or while supplies last. Code(s) redeemable on </em><a href=\"https://id.embark.games/\" target=\"_blank\" rel=\"noopener\"><em>https://id.embark.games</em></a><em> until 11/10/26. Age 13+ only. For full Terms, see </em><a href=\"http://subway.com/en-us/arcraiders\" target=\"_blank\" rel=\"noopener\"><em>Subway.com/en-us/arcraiders.</em></a></p>"
   }
  ]
 },
 {
  "id": "live-update-1-42-0",
  "url": "https://arcraiders.com/news/live-update-1-42-0",
  "date": "2026-08-18",
  "tags": [
   "Patch Notes"
  ],
  "thumb": "https://assets.arcraiders.com/article-cards/17866e04-91ae-store-update-1.42-card-300x100-300x100.png",
  "title": {
   "en": "Live Update 1.42.0"
  },
  "body": [
   {
    "type": "image",
    "html": "<img src=\"https://assets.arcraiders.com/media/c107664e-f682-ARC-Raiders_Steam_EventHeader_LiveUpdate_1920x622%20(1)-1024x332.jpg\" alt=\"\" loading=\"lazy\" width=\"1024\" height=\"332\">"
   },
   {
    "type": "html",
    "en": "<p>Raiders!</p>"
   },
   {
    "type": "html",
    "en": "<p>Update 1.42.0 is going live right now and with it a number of fixes, a second part of the Phantom Targets event with the Anomalia Outfit, a new Player Project, improved map condition scheduling, and new Twitch drops.</p>"
   },
   {
    "type": "html",
    "en": "<h2><strong>HIGHLIGHTS</strong></h2>"
   },
   {
    "type": "html",
    "en": "<ul><li>Phantom Targets Event &amp; Phantom Targets Part 2 Raider Project</li><li>The Tick Hunter Set is now available</li><li>Improved Regional Map Condition Schedule</li><li>An Update on Anti-Cheat and Fair Play</li><li>New Twitch Drops (Car Freshener &amp; Ceramic Vase)</li><li>Rubber Duck Competition Winners</li></ul>"
   },
   {
    "type": "html",
    "en": "<h2><strong>Phantom Targets Revealed</strong></h2>"
   },
   {
    "type": "html",
    "en": "<p>Thanks to the assistance of many Raiders, Shani finally pinpointed the source of the phantom targets: erratic Wasps. These ARC units are exhibiting behavior she’s never seen before: emitting strange noises, flying in irregular patterns, and carrying unidentifiable tech. They’re all swarming towards one location. She needs further assistance to understand what’s waiting for them there.</p>"
   },
   {
    "type": "image",
    "html": "<img src=\"https://assets.arcraiders.com/media/2fa346cc-2883-ArcRaiders_ScreenShot_GlitchedARC_16x9-1024x576.jpg\" alt=\"\" loading=\"lazy\" width=\"1024\" height=\"576\">"
   },
   {
    "type": "html",
    "en": "<h2><strong>Improvements to Map Condition Scheduling </strong></h2>"
   },
   {
    "type": "html",
    "en": "<p>We have been working to make sure that the way we schedule Map Conditions is aligned with your playing habits. To that end, we’re introducing <em>Regional Map Condition Scheduling</em>. Starting with 1.42.0, Map Conditions will have their schedule offset based on regions, instead of a single, global schedule.</p>"
   },
   {
    "type": "html",
    "en": "<p>This means that the schedule will shift to fit specific regions&#x27; peak hours to better match your experience. This way, it’ll be less likely to miss out on a map condition regardless of where you are.</p>"
   },
   {
    "type": "html",
    "en": "<p>Don’t hesitate to tell us how Regional Map Condition schedules are working by chatting with us on our Discord! We’re eager to see what everyone’s experience is like and make adjustments accordingly.</p>"
   },
   {
    "type": "html",
    "en": "<p><em>Note: the </em><a href=\"https://arcraiders.com/map-conditions\" target=\"_blank\" rel=\"noopener\"><em>Map Condition tracker</em></a><em> on the website now reflects this change.</em></p>"
   },
   {
    "type": "html",
    "en": "<h2><strong>Following up about Fair Play </strong></h2>"
   },
   {
    "type": "html",
    "en": "<p>It’s time to look at what’s been going on in the realm of Fair Play since our last chat <a href=\"https://arcraiders.com/news/live-update-1-36-0#maintaining-fair-play\" target=\"_blank\" rel=\"noopener\">a few weeks back</a>. Some new (and some recurring) topics have crossed our path since then, and we wanted to reassure you that keeping Topside safe against cheaters and exploits is a top priority for us, and will continue to be so.</p>"
   },
   {
    "type": "html",
    "en": "<h3><strong>A Note on Third Party Software</strong></h3>"
   },
   {
    "type": "html",
    "en": "<p>When we see reports of third party software being used to gain an advantage of any kind, in-game or at account level, we investigate. The first and most important step is to verify the validity of the report and whether or not the software actually does what it claims to do. A lot of the time, claims are just that, and interacting with this kind of software carries a large amount of risk.<br> <br>Be aware that downloading unverified and unofficial software can put more than just your account at risk. Beyond getting banned and losing access to the game, your data and personal information could be exposed.</p>"
   },
   {
    "type": "html",
    "en": "<p>Remember that your account is only as secure as its weakest link. In order to protect your account, your purchases and progression, we strongly recommend making sure 2FA or passkeys are enabled on all external accounts connected to your Embark ID. Oh, and never share your credentials with anyone. No matter how many ducks they offer.</p>"
   },
   {
    "type": "html",
    "en": "<h3><strong>Recent Actions &amp; Future Plans</strong></h3>"
   },
   {
    "type": "html",
    "en": "<p>Over the past few weeks, we have been making several improvements alongside Anybrain and Denuvo Anti-Cheat. This has resulted in swift action being taken against a large number of accounts that were using recently popularized cheating software.</p>"
   },
   {
    "type": "html",
    "en": "<p>There is also the matter of ensuring permanent sanctions for serial, blatant cheaters. We continue working on methods that make it more difficult for new accounts to be obtained and that discourage cheaters from returning.</p>"
   },
   {
    "type": "html",
    "en": "<p>There have been compounding improvements in our ability to also detect accounts that participated in what we classify as “economy exploits”, which means we can more quickly sanction offenders. These types of sanctions have been ongoing.</p>"
   },
   {
    "type": "html",
    "en": "<p>Additionally, we have several simultaneous initiatives that are meant to address teaming and general matchmaking abuse. We know how important having a consistently good experience is, and that in certain regions or at certain times, it’s easier to run into groups of players that try to force their way into lobbies and engage in griefing. We’ll share more when all of these are ready.</p>"
   },
   {
    "type": "html",
    "en": "<p>And that’s, of course, not all. We’ll keep building up all of the initiatives we mentioned and we’ll do our best to make sure that your experiences across the Rust Belt are fun, thrilling, and most importantly <em>fair</em>.</p>"
   },
   {
    "type": "html",
    "en": "<h2><strong>Congratulations to the Winners of the Rubber Duck Design Contest!</strong></h2>"
   },
   {
    "type": "html",
    "en": "<p>Last Thursday, the 3 finalists of the Rubber Duck Design Contest were selected via popular vote on our <a href=\"https://discord.gg/ekG4VTdg7R\" target=\"_blank\" rel=\"noopener\">Discord</a>. We have since begun working on bringing the ducks into the game, and we will add them in a future update! <br><br>Soon enough, you’ll be able to fill your Raider Den with ducks made by the super-talented <em>gekko.rar, im_AshCheeks and nassguhl. </em></p>"
   },
   {
    "type": "image",
    "html": "<img src=\"https://assets.arcraiders.com/media/898f2a90-a50f-ARC-Raiders_Steam_EventHeader_Ducks_1920x622-1024x332.jpg\" alt=\"\" loading=\"lazy\" width=\"1024\" height=\"332\">"
   },
   {
    "type": "html",
    "en": "<h2></h2>"
   },
   {
    "type": "html",
    "en": "<h2><strong>Content and Bug Fixes</strong></h2>"
   },
   {
    "type": "html",
    "en": "<h3>Audio</h3>"
   },
   {
    "type": "html",
    "en": "<ul><li>Refined footstep and movement sounds indoors: removed scuff sounds, improved audibility at distance, and updated occlusion and concrete surface cues.</li><li>Improved footstep audio when moving through foliage for clearer, more natural sound.</li><li>Added unique footstep sounds when moving over plastic cloth and tarp surfaces.</li><li>Added different audio for all Tier 3 magazine upgrades firing sounds.<br></li></ul>"
   },
   {
    "type": "html",
    "en": "<h3>Gameplay</h3>"
   },
   {
    "type": "html",
    "en": "<ul><li>The Snitch can now call in a Rocketeer. Additionally, it can also call in a Firefly and Hornet duo. Snitch Scanners should not be affected by this change.</li><li>Fixed stomp attacks from the Queen and Matriarch sometimes hitting through walls or from much farther away than intended.</li><li>The Photoelectric Cloak now works against Turbine lightning attacks and Matriarch missiles.</li><li>Added spawn protection to the Surge Coil Trap to avoid affecting players as they spawn in.</li><li>Added the ability to rebind Quick Wheel slots.</li><li>The Dolabra, Hullcracker and Rascal now deal damage correctly in the Practice Range.</li></ul>"
   },
   {
    "type": "html",
    "en": "<h3>Map</h3>"
   },
   {
    "type": "html",
    "en": "<ul><li>Fixed an issue where a zip line in Buried City couldn’t be interacted with by repositioning it to ensure it can be used.</li></ul>"
   },
   {
    "type": "html",
    "en": "<h3>Performance</h3>"
   },
   {
    "type": "html",
    "en": "<ul><li>Improved UI texture streaming cache for better memory efficiency and reliability.  </li></ul>"
   },
   {
    "type": "html",
    "en": "<h3>Stability</h3>"
   },
   {
    "type": "html",
    "en": "<ul><li>Fixed several crashes and made various improvements to stability.</li></ul>"
   },
   {
    "type": "html",
    "en": "<h3>UI</h3>"
   },
   {
    "type": "html",
    "en": "<ul><li>Fixed project tiles incorrectly showing “Part X completed” on projects without parts.</li><li>Corrected spelling errors and updated localized text across multiple languages.</li><li>Polished matchmaking error messages for clarity.</li><li>Completed project quests now correctly bring you to the associated project page when pressing the “Claim” shortcut button in the logbook.</li><li>Added a Region label on the Map selection screen, which displays your current Matchmaking region.</li></ul>"
   },
   {
    "type": "html",
    "en": "<h2><strong>KNOWN ISSUES</strong></h2>"
   },
   {
    "type": "html",
    "en": "<ul><li>We’re continuing to investigate reports of crashes on XBOX Series S. We apologize for the inconvenience and thank you for your reports. As soon as we know more, we’ll let you know. </li><li>We’re aware of issues with crashing on PC, related to Windows Update KB5121003. Please consult our <a href=\"https://discord.com/channels/1107589599045361695/1107613897357275188/1537853764193624105\" target=\"_blank\" rel=\"noopener\">workaround shared here</a> while we work on a fix.</li><li>Players on Epic may experience a sudden loss of keyboard input.</li><li><ul><li>While we look into this, we recommend disabling any Overlay you may have active. Additionally, you can try alt-tabbing out and back into the game.</li></ul></li><li>The Projects tab has a sticky notification dot.</li><li>The throw animation may sometimes fail to play when attempting to detonate a Trigger ‘Nade immediately after throwing it.</li><li>The weapon swap animation may appear broken if weapon swapping right after vaulting.</li><li>Player animations may appear broken when interrupting a search of the Baron Husk.</li><li>Shredders float to the ceiling in some rooms of the Hidden Bunker.</li><li>Leapers can jump through the ARC Turbine.</li><li>When bringing items that give Merits with you into a Raid, the items will wrongfully display a Merits icon.</li><li>Shots taken while riding ARC may not register correctly.</li><li>Some doors may allow player flashlights’ beams to pass through instead of blocking the emitted light.</li><li>We are aware of some clipping issues with the Triumph, Reaver and Azimuth outfits.</li><li>Old Ermal offers may appear to be available in the &#x27;Acquire and Craft&#x27; menu (visual only).</li></ul>"
   },
   {
    "type": "html",
    "en": "<p>See you Topside,<br>//Ossen &amp; Raz</p>"
   }
  ]
 },
 {
  "id": "frozen-trail-is-coming-october-8th",
  "url": "https://arcraiders.com/news/frozen-trail-is-coming-october-8th",
  "date": "2026-08-12",
  "tags": [],
  "thumb": "https://assets.arcraiders.com/article-cards/7ba2a90c-db37-ArcRaiders_Blogs_GeneralAsset_PatchNotes_300x100-300x100.png",
  "title": {
   "en": "Frozen Trail is coming October 8!"
  },
  "body": [
   {
    "type": "image",
    "html": "<img src=\"https://assets.arcraiders.com/media/e3b333c7-1a2f-ARC%20Raiders_Blog_Header_DevUpdate_1920x622_3-1024x332.png\" alt=\"\" loading=\"lazy\" width=\"1024\" height=\"332\">"
   },
   {
    "type": "html",
    "en": "<p><strong>Greetings from Embark, Raiders!</strong></p>"
   },
   {
    "type": "html",
    "en": "<p>As we head toward October, the Frozen Trail update draws closer. We wanted to take a moment to share what we’ve been working on since we communicated <a href=\"https://arcraiders.com/news/development-update\" target=\"_blank\" rel=\"noopener\">how we’re changing updates</a>.</p>"
   },
   {
    "type": "html",
    "en": "<p>Back in May, we shared that we’d be moving to fewer, larger updates. We know that means longer stretches between major releases, and we appreciate everyone who has stuck with us while we’ve continued to ship new content like projects, events, a new Trader, and ongoing improvements based on your feedback!</p>"
   },
   {
    "type": "html",
    "en": "<p>Behind the scenes, our focus has been firmly on Frozen Trail. It’s going to be our biggest update since launch, and it’s been designed to address some of the broader questions that the community has been asking. Nearly every part of the game has benefited from what we’ve learned over the past few months. Here’s a look at some of what we’ve been working on.</p>"
   },
   {
    "type": "html",
    "en": "<h3><strong>The Next Frontier</strong></h3>"
   },
   {
    "type": "html",
    "en": "<p>At the heart of Frozen Trail is our newest map. Shani will call upon Raiders to investigate an unprecedented signal emanating from beyond the mountains. Something big has happened here – could anyone resist being a part of the initial scouting party? </p>"
   },
   {
    "type": "image",
    "html": "<img src=\"https://assets.arcraiders.com/media/ArcRaiders_ScreenShot_16x9_04-1024x576.jpg\" alt=\"\" loading=\"lazy\" width=\"1024\" height=\"576\">"
   },
   {
    "type": "html",
    "en": "<p>Explore a harsh, frozen settlement nestled beneath towering mountains at the edge of the Rust Belt. Once home to thriving villages, factories, research facilities, and an observatory, long since abandoned.</p>"
   },
   {
    "type": "html",
    "en": "<p>Building the new map has challenged our level design team in exciting new ways. We’ve focused on creating an ambitious environment with greater verticality, exploration, and opportunities for discovery. You’ll encounter threats above and below ground, and navigate environments that no Raiders have seen before. </p>"
   },
   {
    "type": "html",
    "en": "<p>We’ve recently completed a round of user experience research testing, and our team is currently iterating to ensure the new map is as exciting as possible.</p>"
   },
   {
    "type": "html",
    "en": "<h3><strong>New High-level Challenge</strong></h3>"
   },
   {
    "type": "html",
    "en": "<p>The Frozen Trail update will also introduce an enormous new ARC Operation designed for experienced Raiders looking to push themselves even further.</p>"
   },
   {
    "type": "html",
    "en": "<p>Without giving too much away, this new activity is built around many of the ideas that have become increasingly important to us throughout development: meaningful decisions, dynamic encounters, and moments that demand cooperation and careful judgment.</p>"
   },
   {
    "type": "html",
    "en": "<p>Success won’t come easily. You’ll need to balance combat, teamwork, risk, and survival in what we believe will be one of the most intense experiences ARC Raiders has offered to date – one that rewards those willing to rise to the challenge.</p>"
   },
   {
    "type": "html",
    "en": "<p>We’ll save more details for the full reveal later – but we’re excited for you to experience it for yourselves.</p>"
   },
   {
    "type": "html",
    "en": "<h3><strong>New ARC, New Threats</strong></h3>"
   },
   {
    "type": "html",
    "en": "<p>Our team has been hard at work developing new ARC threats that will arrive alongside the new map, each designed to challenge the ways you’ve learned to move, fight, and adapt. These new ARC enemies range from a small and nifty problem-maker to an enormous machine that will halt you in your tracks. </p>"
   },
   {
    "type": "html",
    "en": "<p>Creating new ARC is one of the more involved parts of development. From early concepts and animation to behavior and machine learning systems that give them their distinctive “spark of life”, every enemy goes through months of iteration to get right. We think it’ll be worth the wait, and we can’t wait to see what you think.</p>"
   },
   {
    "type": "html",
    "en": "<h3><strong>Deepening Progression</strong></h3>"
   },
   {
    "type": "html",
    "en": "<p>Frozen Trail is also evolving what it means to be a Raider.</p>"
   },
   {
    "type": "html",
    "en": "<p>One lesson that’s continued to shape our thinking is that the most rewarding raids are driven by meaningful choices. That’s influenced how we’re approaching progression throughout Frozen Trail, allowing you to build a deeper identity in the Rust Belt. </p>"
   },
   {
    "type": "html",
    "en": "<p>Your Raider Den has served you well, but it’s time to expand. We&#x27;re building deeper progression systems, giving players more ways to craft their own journey and build toward long-term goals. </p>"
   },
   {
    "type": "html",
    "en": "<p>That’s why your Raider will have the opportunity to inhabit a new space; the Outpost. After spending months on the back foot, hiding underground, it’s time to start taking the fight to ARC. Decorate your Outpost, research new elements of the world, and take your first steps to reclaiming the surface.</p>"
   },
   {
    "type": "html",
    "en": "<p>On top of Outposts, we’re also adjusting the Skill Tree to give you more agency over the kind of Raider you want to become. Raider Decks have also been on our radar, with the focus on making them more engaging and rewarding for players. </p>"
   },
   {
    "type": "image",
    "html": "<img src=\"https://assets.arcraiders.com/media/5d36182d-f462-ArcRaiders_ScreenShot_16x9_03-1024x576.jpg\" alt=\"\" loading=\"lazy\" width=\"1024\" height=\"576\">"
   },
   {
    "type": "html",
    "en": "<h3><strong>And More…</strong></h3>"
   },
   {
    "type": "html",
    "en": "<p>These are just a few of the additions coming in Frozen Trail.</p>"
   },
   {
    "type": "html",
    "en": "<p>The team is continuing to work on new content that will enhance your experience, as well as new weapons (and ways to personalize them!), gadgets, cosmetics, instruments, and plenty of other surprises we’ll talk about closer to launch. </p>"
   },
   {
    "type": "html",
    "en": "<p>Alongside all of that, we&#x27;ll continue improving the core ARC Raiders experience through ongoing work on matchmaking, anti-cheat, stability, and quality-of-life updates. While these improvements may not always be the headline features, they remain a critical part of making every raid feel balanced and enjoyable. </p>"
   },
   {
    "type": "html",
    "en": "<p>You’ll be able to experience Frozen Trail for yourself on October 8, and we will be sharing more details with you in September. </p>"
   },
   {
    "type": "html",
    "en": "<p>Until then, if you’re heading to gamescom in Cologne, come say hello! We’d love to meet you and see you experience ARC Raiders in person.</p>"
   },
   {
    "type": "html",
    "en": "<p>See you topside,</p>"
   },
   {
    "type": "html",
    "en": "<p>Aleksander Grøndal</p>"
   },
   {
    "type": "html",
    "en": "<p>Executive Producer</p>"
   }
  ]
 },
 {
  "id": "store-update-1-41-0",
  "url": "https://arcraiders.com/news/store-update-1-41-0",
  "date": "2026-08-11",
  "tags": [
   "Store Update"
  ],
  "thumb": "https://assets.arcraiders.com/article-cards/9f1dc4b5-342d-store-update-1.41-card-300x100-300x100.png",
  "title": {
   "en": "Store Update 1.41.0"
  },
  "body": [
   {
    "type": "image",
    "html": "<img src=\"https://assets.arcraiders.com/media/255e01cb-27d1-ARC-Raiders_Blog_EventHeader_StoreUpdate_1920x622%20(2)-1024x332.jpg\" alt=\"\" loading=\"lazy\" width=\"1024\" height=\"332\">"
   },
   {
    "type": "html",
    "en": "<p>Raiders!</p>"
   },
   {
    "type": "html",
    "en": "<p>Store Update 1.41.0 is going live right now and brings two new colour variants for the Vulpine outfit (green/camo and black). If you already own the outfit, you will get the colour variants automatically. No restart required.</p>"
   },
   {
    "type": "html",
    "en": "<p>We’re also deploying a small hotfix for Steam players, aimed at fixing a variety of crashes and errors that occur when launching the game. Thank you for the reports around these issues.</p>"
   },
   {
    "type": "html",
    "en": "<p>See you Topside,<br>//Ossen</p>"
   }
  ]
 }
];
